stages:
  - lint
  - fixtures
  - test
  - publish

.publish-package: &publish-package
  - python3 setup.py sdist bdist_wheel
  - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/* --verbose
  - TWINE_PASSWORD=${PYPI_API_TOKEN} TWINE_USERNAME=${PYPI_API_USERNAME} python -m twine upload dist/* --verbose


lint:
  stage: lint
  image: softozor/python-lint:$TOOLS_SHA
  script:
    - autopep8 -rd . --exit-code

publish-alpine-with-file:
  stage: fixtures
  image: docker:latest
  variables:
    DOCKER_IMAGE: softozor/alpine-with-file
    DOCKERFILE_FOLDER: ./test/docker/alpine-with-file
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build $DOCKERFILE_FOLDER -t $DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA -t $DOCKER_IMAGE:latest
    - docker push $DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $DOCKER_IMAGE:latest
  only:
    changes:
      - $CI_PROJECT_DIR/test/docker/alpine-with-file/*

test:
  stage: test
  image: softozor/python-tests:$TOOLS_SHA
  variables:
    PYTHONPATH: $CI_PROJECT_DIR
  before_script:
    - python setup.py install
    - cd test
  script:
    - |
      pytest -p no:cacheprovider -ra -vv --junitxml=$CI_PROJECT_DIR/test-reports/test-report.xml \
        -n 4 \
        --api-url $JELASTIC_API_URL \
        --api-token $JELASTIC_ACCESS_TOKEN \
        --test-data-dir ./data \
        --jelastic-version $JELASTIC_VERSION \
        --commit-sha $CI_COMMIT_SHORT_SHA
  artifacts:
    reports:
      junit:
        - $CI_PROJECT_DIR/test-reports/*.xml
    paths:
      - $CI_PROJECT_DIR/test-reports

publish-patch:
  stage: publish
  image: softozor/python-publish:$TOOLS_SHA
  variables:
    PACKAGE_NAME: jelastic-client
  before_script:
    - export JELASTIC_CLIENT_VERSION=$(python3 /usr/local/bin/get_latest_package_version.py --package-name $PACKAGE_NAME --package-type pypi)
  script:
    - *publish-package
  only:
    refs:
      - master
    changes:
      - jelastic_client/**/*
      - setup.py

publish-minor:
  stage: publish
  image: softozor/python-publish:$TOOLS_SHA
  variables:
    PACKAGE_NAME: jelastic-client
  before_script:
    - export JELASTIC_CLIENT_VERSION=$(python3 /usr/local/bin/get_latest_package_version.py --package-name $PACKAGE_NAME --package-type pypi --increase-version minor)
  script:
    - *publish-package
  when: manual
  only:
    refs:
      - master
    changes:
      - jelastic_client/**/*
      - setup.py

publish-major:
  stage: publish
  image: softozor/python-publish:$TOOLS_SHA
  variables:
    PACKAGE_NAME: jelastic-client
  before_script:
    - export JELASTIC_CLIENT_VERSION=$(python3 /usr/local/bin/get_latest_package_version.py --package-name $PACKAGE_NAME --package-type pypi --increase-version major)
  script:
    - *publish-package
  when: manual
  only:
    refs:
      - master
    changes:
      - jelastic_client/**/*
      - setup.py