stages:
  - lint
  - test
  - publish

lint:
  stage: lint
  image: softozor/python-lint:$TOOLS_SHA
  script:
    - autopep8 -rd . --exit-code

test:
  stage: test
  image: softozor/python-tests:$TOOLS_SHA
  variables:
    PYTHONPATH: $CI_PROJECT_DIR
  before_script:
    - python setup.py install
    - cd test
  script:
    - |
      pytest -p no:cacheprovider -ra -vv --junitxml=$CI_PROJECT_DIR/test-reports/test-report.xml \
        -n 4 \
        --api-url $JELASTIC_API_URL \
        --api-token $JELASTIC_ACCESS_TOKEN \
        --test-data-dir ./data \
        --jelastic-version $JELASTIC_VERSION
  artifacts:
    reports:
      junit:
        - $CI_PROJECT_DIR/test-reports/*.xml
    paths:
      - $CI_PROJECT_DIR/test-reports

publish:
  stage: publish
  image: softozor/python-publish:$TOOLS_SHA
  variables:
    PACKAGE_NAME: jelastic-client
  before_script:
    - export JELASTIC_CLIENT_VERSION=$(python3 /usr/local/bin/get_latest_package_version.py --package-name $PACKAGE_NAME --package-type pypi)
  script:
    - python3 setup.py sdist bdist_wheel
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*
    - TWINE_PASSWORD=${PYPI_API_TOKEN} TWINE_USERNAME=${PYPI_API_USERNAME} python -m twine upload dist/*
  only:
    refs:
      - master
    changes:
      - jelastic_client/**/*
      - setup.py