package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'ReleaseToPypi'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("ReleaseToPypi")) {
    vcs {

        check(cleanCheckout == false) {
            "Unexpected option value: cleanCheckout = $cleanCheckout"
        }
        cleanCheckout = true

        check(branchFilter == "+:*") {
            "Unexpected option value: branchFilter = $branchFilter"
        }
        branchFilter = """
            +:v*
            -:<default>
        """.trimIndent()
    }
}
